


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."is_admin"() RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  select exists (
    select 1
    from public.profiles as p
    where p.id = (select auth.uid())
      and p.is_admin is true
  );
$$;


ALTER FUNCTION "public"."is_admin"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."sync_game_release_to_catalog"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  insert into public.game_platforms (
    game_id,
    platform_id,
    region,
    release_date,
    physical,
    digital,
    edition_name
  )
  values (
    new.game_id,
    new.platform_id,
    coalesce(new.region, 'WORLD'),
    new.release_date,
    coalesce(new.physical, false),
    coalesce(new.digital, false),
    new.edition_name
  )
  on conflict (game_id, platform_id, region)
  do update set
    release_date = coalesce(
      excluded.release_date,
      public.game_platforms.release_date
    ),
    physical = public.game_platforms.physical or excluded.physical,
    digital = public.game_platforms.digital or excluded.digital,
    edition_name = coalesce(
      excluded.edition_name,
      public.game_platforms.edition_name
    ),
    updated_at = now();

  return new;
end;
$$;


ALTER FUNCTION "public"."sync_game_release_to_catalog"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."admin_users" (
    "user_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."admin_users" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."game_platforms" (
    "id" bigint NOT NULL,
    "game_id" bigint NOT NULL,
    "platform_id" bigint NOT NULL,
    "region" "text" DEFAULT 'WORLD'::"text" NOT NULL,
    "release_date" "date",
    "physical" boolean DEFAULT false NOT NULL,
    "digital" boolean DEFAULT false NOT NULL,
    "edition_name" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "game_platforms_region_check" CHECK (("region" = ANY (ARRAY['PAL'::"text", 'US'::"text", 'JAP'::"text", 'ASIA'::"text", 'WORLD'::"text"])))
);


ALTER TABLE "public"."game_platforms" OWNER TO "postgres";


ALTER TABLE "public"."game_platforms" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."game_platforms_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."game_releases" (
    "id" bigint NOT NULL,
    "game_id" bigint NOT NULL,
    "platform_id" bigint NOT NULL,
    "region" "text" DEFAULT 'WORLD'::"text" NOT NULL,
    "release_date" "date",
    "physical" boolean DEFAULT false,
    "digital" boolean DEFAULT true,
    "status" "text" DEFAULT 'confirmed'::"text",
    "edition_name" "text",
    CONSTRAINT "game_releases_region_check" CHECK (("region" = ANY (ARRAY['PAL'::"text", 'US'::"text", 'JAP'::"text", 'ASIA'::"text", 'WORLD'::"text"]))),
    CONSTRAINT "game_releases_status_check" CHECK (("status" = ANY (ARRAY['confirmed'::"text", 'rumor'::"text", 'delayed'::"text", 'released'::"text"])))
);


ALTER TABLE "public"."game_releases" OWNER TO "postgres";


ALTER TABLE "public"."game_releases" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."game_releases_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."game_tags" (
    "game_id" bigint NOT NULL,
    "tag_id" bigint NOT NULL
);


ALTER TABLE "public"."game_tags" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."games" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "description" "text",
    "developer" "text",
    "publisher" "text",
    "series" "text",
    "cover_url" "text",
    "release_year" integer,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "original_title" "text",
    "synopsis" "text",
    "combat_system" "text",
    "player_count" "text",
    "estimated_duration" "text",
    "age_rating" "text",
    "director" "text",
    "composer" "text",
    "official_website" "text"
);


ALTER TABLE "public"."games" OWNER TO "postgres";


ALTER TABLE "public"."games" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."games_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."news" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "summary" "text" NOT NULL,
    "content" "text",
    "source_url" "text",
    "related_game_id" bigint,
    "published_at" timestamp with time zone DEFAULT "now"(),
    "excerpt" "text",
    "image_url" "text",
    "category" "text",
    "source_name" "text",
    "status" "text" DEFAULT 'draft'::"text" NOT NULL,
    "author_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "news_status_check" CHECK (("status" = ANY (ARRAY['draft'::"text", 'published'::"text"])))
);


ALTER TABLE "public"."news" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."news_games" (
    "news_id" bigint NOT NULL,
    "game_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."news_games" OWNER TO "postgres";


ALTER TABLE "public"."news" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."news_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."platforms" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "manufacturer" "text",
    "slug" "text" NOT NULL,
    "generation" smallint,
    "launch_year" smallint,
    "is_legacy" boolean DEFAULT false NOT NULL,
    "display_order" integer DEFAULT 0 NOT NULL,
    CONSTRAINT "platforms_generation_check" CHECK ((("generation" IS NULL) OR (("generation" >= 1) AND ("generation" <= 20)))),
    CONSTRAINT "platforms_launch_year_check" CHECK ((("launch_year" IS NULL) OR (("launch_year" >= 1970) AND ("launch_year" <= 2100))))
);


ALTER TABLE "public"."platforms" OWNER TO "postgres";


ALTER TABLE "public"."platforms" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."platforms_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "username" "text",
    "display_name" "text",
    "avatar_url" "text",
    "is_admin" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."tags" OWNER TO "postgres";


ALTER TABLE "public"."tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_collections" (
    "id" bigint NOT NULL,
    "user_id" "uuid",
    "game_id" bigint,
    "platform_id" bigint,
    "status" "text" DEFAULT 'owned'::"text",
    "format" "text" DEFAULT 'physical'::"text",
    "region" "text" DEFAULT 'PAL'::"text",
    "personal_rating" integer,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "user_collections_format_check" CHECK (("format" = ANY (ARRAY['physical'::"text", 'digital'::"text", 'both'::"text"]))),
    CONSTRAINT "user_collections_personal_rating_check" CHECK ((("personal_rating" >= 0) AND ("personal_rating" <= 10))),
    CONSTRAINT "user_collections_region_check" CHECK (("region" = ANY (ARRAY['PAL'::"text", 'US'::"text", 'JAP'::"text", 'ASIA'::"text", 'WORLD'::"text"]))),
    CONSTRAINT "user_collections_status_check" CHECK (("status" = ANY (ARRAY['owned'::"text", 'playing'::"text", 'completed'::"text", 'backlog'::"text", 'wishlist'::"text", 'preordered'::"text", 'abandoned'::"text"])))
);


ALTER TABLE "public"."user_collections" OWNER TO "postgres";


ALTER TABLE "public"."user_collections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_collections_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_followed_games" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "game_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."user_followed_games" OWNER TO "postgres";


ALTER TABLE "public"."user_followed_games" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_followed_games_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."admin_users"
    ADD CONSTRAINT "admin_users_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."game_platforms"
    ADD CONSTRAINT "game_platforms_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."game_releases"
    ADD CONSTRAINT "game_releases_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."game_tags"
    ADD CONSTRAINT "game_tags_pkey" PRIMARY KEY ("game_id", "tag_id");



ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."news_games"
    ADD CONSTRAINT "news_games_pkey" PRIMARY KEY ("news_id", "game_id");



ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."platforms"
    ADD CONSTRAINT "platforms_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."platforms"
    ADD CONSTRAINT "platforms_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_collections"
    ADD CONSTRAINT "user_collections_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_collections"
    ADD CONSTRAINT "user_collections_user_id_game_id_platform_id_region_format_key" UNIQUE ("user_id", "game_id", "platform_id", "region", "format");



ALTER TABLE ONLY "public"."user_followed_games"
    ADD CONSTRAINT "user_followed_games_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_followed_games"
    ADD CONSTRAINT "user_followed_games_user_id_game_id_key" UNIQUE ("user_id", "game_id");



CREATE INDEX "game_platforms_game_id_idx" ON "public"."game_platforms" USING "btree" ("game_id");



CREATE UNIQUE INDEX "game_platforms_game_platform_region_uidx" ON "public"."game_platforms" USING "btree" ("game_id", "platform_id", "region");



CREATE INDEX "game_platforms_platform_id_idx" ON "public"."game_platforms" USING "btree" ("platform_id");



CREATE INDEX "game_releases_game_id_idx" ON "public"."game_releases" USING "btree" ("game_id");



CREATE UNIQUE INDEX "game_releases_game_platform_region_uidx" ON "public"."game_releases" USING "btree" ("game_id", "platform_id", "region");



CREATE INDEX "game_releases_platform_id_idx" ON "public"."game_releases" USING "btree" ("platform_id");



CREATE INDEX "game_releases_release_date_idx" ON "public"."game_releases" USING "btree" ("release_date");



CREATE UNIQUE INDEX "games_slug_lower_uidx" ON "public"."games" USING "btree" ("lower"("slug"));



CREATE INDEX "news_games_game_id_idx" ON "public"."news_games" USING "btree" ("game_id");



CREATE INDEX "news_games_news_id_idx" ON "public"."news_games" USING "btree" ("news_id");



CREATE INDEX "news_publication_index" ON "public"."news" USING "btree" ("status", "published_at" DESC);



CREATE UNIQUE INDEX "news_slug_unique_index" ON "public"."news" USING "btree" ("slug");



CREATE UNIQUE INDEX "platforms_slug_lower_uidx" ON "public"."platforms" USING "btree" ("lower"("slug"));



CREATE OR REPLACE TRIGGER "sync_game_release_to_catalog_trigger" AFTER INSERT OR UPDATE OF "game_id", "platform_id", "region", "release_date", "physical", "digital", "edition_name" ON "public"."game_releases" FOR EACH ROW EXECUTE FUNCTION "public"."sync_game_release_to_catalog"();



ALTER TABLE ONLY "public"."admin_users"
    ADD CONSTRAINT "admin_users_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_platforms"
    ADD CONSTRAINT "game_platforms_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_platforms"
    ADD CONSTRAINT "game_platforms_platform_id_fkey" FOREIGN KEY ("platform_id") REFERENCES "public"."platforms"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."game_releases"
    ADD CONSTRAINT "game_releases_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_releases"
    ADD CONSTRAINT "game_releases_platform_id_fkey" FOREIGN KEY ("platform_id") REFERENCES "public"."platforms"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."game_tags"
    ADD CONSTRAINT "game_tags_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_tags"
    ADD CONSTRAINT "game_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."news_games"
    ADD CONSTRAINT "news_games_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."news_games"
    ADD CONSTRAINT "news_games_news_id_fkey" FOREIGN KEY ("news_id") REFERENCES "public"."news"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_related_game_id_fkey" FOREIGN KEY ("related_game_id") REFERENCES "public"."games"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_collections"
    ADD CONSTRAINT "user_collections_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_collections"
    ADD CONSTRAINT "user_collections_platform_id_fkey" FOREIGN KEY ("platform_id") REFERENCES "public"."platforms"("id");



ALTER TABLE ONLY "public"."user_collections"
    ADD CONSTRAINT "user_collections_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_followed_games"
    ADD CONSTRAINT "user_followed_games_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_followed_games"
    ADD CONSTRAINT "user_followed_games_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Admins can create news" ON "public"."news" FOR INSERT TO "authenticated" WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "Admins can delete news" ON "public"."news" FOR DELETE TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "Admins can read all news" ON "public"."news" FOR SELECT TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "Admins can update news" ON "public"."news" FOR UPDATE TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin")) WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "Anyone can read news" ON "public"."news" FOR SELECT USING (true);



CREATE POLICY "Published news are public" ON "public"."news" FOR SELECT TO "authenticated", "anon" USING ((("status" = 'published'::"text") AND ("published_at" IS NOT NULL) AND ("published_at" <= "now"())));



CREATE POLICY "Users can delete from their own collection" ON "public"."user_collections" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Users can delete their own collection" ON "public"."user_collections" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Users can follow games" ON "public"."user_followed_games" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Users can insert into their own collection" ON "public"."user_collections" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Users can read their followed games" ON "public"."user_followed_games" FOR SELECT USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Users can read their own collection" ON "public"."user_collections" FOR SELECT USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Users can read their own profile" ON "public"."profiles" FOR SELECT USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Users can unfollow games" ON "public"."user_followed_games" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Users can update their own collection" ON "public"."user_collections" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



ALTER TABLE "public"."admin_users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."game_platforms" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "game_platforms_admin_delete" ON "public"."game_platforms" FOR DELETE TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "game_platforms_admin_insert" ON "public"."game_platforms" FOR INSERT TO "authenticated" WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "game_platforms_admin_update" ON "public"."game_platforms" FOR UPDATE TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin")) WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "game_platforms_public_read" ON "public"."game_platforms" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."game_releases" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "game_releases_admin_delete" ON "public"."game_releases" FOR DELETE TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "game_releases_admin_insert" ON "public"."game_releases" FOR INSERT TO "authenticated" WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "game_releases_admin_update" ON "public"."game_releases" FOR UPDATE TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin")) WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "game_releases_public_read" ON "public"."game_releases" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."game_tags" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."games" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "games_admin_delete" ON "public"."games" FOR DELETE TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "games_admin_insert" ON "public"."games" FOR INSERT TO "authenticated" WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "games_admin_update" ON "public"."games" FOR UPDATE TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin")) WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "games_public_read" ON "public"."games" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."news" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."news_games" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "news_games_admin_delete" ON "public"."news_games" FOR DELETE TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "news_games_admin_insert" ON "public"."news_games" FOR INSERT TO "authenticated" WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "news_games_public_read" ON "public"."news_games" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."platforms" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "platforms_admin_delete" ON "public"."platforms" FOR DELETE TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "platforms_admin_insert" ON "public"."platforms" FOR INSERT TO "authenticated" WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "platforms_admin_update" ON "public"."platforms" FOR UPDATE TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin")) WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "platforms_public_read" ON "public"."platforms" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tags" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_collections" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_followed_games" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



REVOKE ALL ON FUNCTION "public"."is_admin"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."is_admin"() TO "anon";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "service_role";



GRANT ALL ON FUNCTION "public"."sync_game_release_to_catalog"() TO "anon";
GRANT ALL ON FUNCTION "public"."sync_game_release_to_catalog"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."sync_game_release_to_catalog"() TO "service_role";



GRANT ALL ON TABLE "public"."admin_users" TO "service_role";



GRANT ALL ON TABLE "public"."game_platforms" TO "anon";
GRANT ALL ON TABLE "public"."game_platforms" TO "authenticated";
GRANT ALL ON TABLE "public"."game_platforms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."game_platforms_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."game_platforms_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."game_platforms_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."game_releases" TO "anon";
GRANT ALL ON TABLE "public"."game_releases" TO "authenticated";
GRANT ALL ON TABLE "public"."game_releases" TO "service_role";



GRANT ALL ON SEQUENCE "public"."game_releases_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."game_releases_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."game_releases_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."game_tags" TO "anon";
GRANT ALL ON TABLE "public"."game_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."game_tags" TO "service_role";



GRANT ALL ON TABLE "public"."games" TO "anon";
GRANT ALL ON TABLE "public"."games" TO "authenticated";
GRANT ALL ON TABLE "public"."games" TO "service_role";



GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."news" TO "anon";
GRANT ALL ON TABLE "public"."news" TO "authenticated";
GRANT ALL ON TABLE "public"."news" TO "service_role";



GRANT ALL ON TABLE "public"."news_games" TO "anon";
GRANT ALL ON TABLE "public"."news_games" TO "authenticated";
GRANT ALL ON TABLE "public"."news_games" TO "service_role";



GRANT ALL ON SEQUENCE "public"."news_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."news_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."news_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."platforms" TO "anon";
GRANT ALL ON TABLE "public"."platforms" TO "authenticated";
GRANT ALL ON TABLE "public"."platforms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."platforms_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."platforms_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."platforms_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_collections" TO "anon";
GRANT ALL ON TABLE "public"."user_collections" TO "authenticated";
GRANT ALL ON TABLE "public"."user_collections" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_collections_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_collections_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_collections_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_followed_games" TO "anon";
GRANT ALL ON TABLE "public"."user_followed_games" TO "authenticated";
GRANT ALL ON TABLE "public"."user_followed_games" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_followed_games_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_followed_games_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_followed_games_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







