-- JRPG Vault
-- Sépare les plateformes disponibles dans le catalogue des sorties calendaires.
--
-- games
--   ├── game_platforms : versions/supports réellement disponibles
--   └── game_releases  : sorties datées affichées dans le calendrier

begin;

create table if not exists public.game_platforms (
  id bigint generated by default as identity primary key,
  game_id bigint not null
    references public.games(id)
    on delete cascade,
  platform_id bigint not null
    references public.platforms(id)
    on delete restrict,
  region text not null default 'WORLD',
  release_date date,
  physical boolean not null default false,
  digital boolean not null default false,
  edition_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'game_platforms_region_check'
      and conrelid = 'public.game_platforms'::regclass
  ) then
    alter table public.game_platforms
      add constraint game_platforms_region_check
      check (region in ('PAL', 'US', 'JAP', 'ASIA', 'WORLD'));
  end if;
end
$$;

create unique index if not exists game_platforms_game_platform_region_uidx
  on public.game_platforms (game_id, platform_id, region);

create index if not exists game_platforms_game_id_idx
  on public.game_platforms (game_id);

create index if not exists game_platforms_platform_id_idx
  on public.game_platforms (platform_id);

-- Les sorties déjà existantes deviennent aussi des versions disponibles
-- dans le catalogue. Les lignes de game_releases restent inchangées.
insert into public.game_platforms (
  game_id,
  platform_id,
  region,
  release_date,
  physical,
  digital,
  edition_name
)
select
  gr.game_id,
  gr.platform_id,
  coalesce(gr.region, 'WORLD'),
  gr.release_date,
  coalesce(gr.physical, false),
  coalesce(gr.digital, false),
  gr.edition_name
from public.game_releases as gr
on conflict (game_id, platform_id, region)
do update set
  release_date = coalesce(
    excluded.release_date,
    public.game_platforms.release_date
  ),
  physical = public.game_platforms.physical or excluded.physical,
  digital = public.game_platforms.digital or excluded.digital,
  edition_name = coalesce(
    excluded.edition_name,
    public.game_platforms.edition_name
  ),
  updated_at = now();

-- Toute future sortie créée dans l'administration ajoute automatiquement
-- le support correspondant au catalogue.
create or replace function public.sync_game_release_to_catalog()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.game_platforms (
    game_id,
    platform_id,
    region,
    release_date,
    physical,
    digital,
    edition_name
  )
  values (
    new.game_id,
    new.platform_id,
    coalesce(new.region, 'WORLD'),
    new.release_date,
    coalesce(new.physical, false),
    coalesce(new.digital, false),
    new.edition_name
  )
  on conflict (game_id, platform_id, region)
  do update set
    release_date = coalesce(
      excluded.release_date,
      public.game_platforms.release_date
    ),
    physical = public.game_platforms.physical or excluded.physical,
    digital = public.game_platforms.digital or excluded.digital,
    edition_name = coalesce(
      excluded.edition_name,
      public.game_platforms.edition_name
    ),
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists sync_game_release_to_catalog_trigger
on public.game_releases;

create trigger sync_game_release_to_catalog_trigger
after insert or update of
  game_id,
  platform_id,
  region,
  release_date,
  physical,
  digital,
  edition_name
on public.game_releases
for each row
execute function public.sync_game_release_to_catalog();

alter table public.game_platforms enable row level security;

drop policy if exists "game_platforms_public_read"
on public.game_platforms;

drop policy if exists "game_platforms_admin_insert"
on public.game_platforms;

drop policy if exists "game_platforms_admin_update"
on public.game_platforms;

drop policy if exists "game_platforms_admin_delete"
on public.game_platforms;

create policy "game_platforms_public_read"
on public.game_platforms
for select
to anon, authenticated
using (true);

create policy "game_platforms_admin_insert"
on public.game_platforms
for insert
to authenticated
with check ((select public.is_admin()));

create policy "game_platforms_admin_update"
on public.game_platforms
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "game_platforms_admin_delete"
on public.game_platforms
for delete
to authenticated
using ((select public.is_admin()));

commit;

-- Vérification :
-- select
--   g.title,
--   p.name as platform,
--   gp.region,
--   gp.release_date,
--   gp.physical,
--   gp.digital
-- from public.game_platforms gp
-- join public.games g on g.id = gp.game_id
-- join public.platforms p on p.id = gp.platform_id
-- order by g.title, p.name, gp.region;
